### ISSUE TITLE
i can´t play

### ISSUE THREAD

**Issue by NooB1234-alt** [Y8Games/Y8-Flash-Browser#2]

**Comment by EddieOne** [comment]
Hello, can you describe the problem in more detail?

**Comment by EMMAROSA11** [comment]
i want to ublock the flash games with adobe

**Comment by EddieOne** [comment]
Where you able to install the Y8 Browser? You will need to download and open the correct file from here. https://github.com/Y8Games/Y8-Flash-Browser/releases

**Comment by magmillen** [comment]
> i want to ublock the flash games with adobe

me too,but.give a few days like 2 days?or something.just wait

**Comment by magmillen** [comment]
guys,how to UNBLOCK ADOBE FLASH PLAYER??????I WANNA PLAY "ORION SANDBOX ENHANCED"pls help me

**Comment by EddieOne** [comment]
Hello, there is a new easier download link here. https://www.y8.com/download-app

1. Download Y8 Browser (for desktop)
2. Install the app
3. Open the app and your ready to play Flash again

**Comment by gogogo228** [comment]
I downloaded the browser on linux, and I got the error "failed to load the plugin".
