### ISSUE TITLE
Santiago hoyos1023

### ISSUE THREAD

**Issue by santi432** [Y8Games/Y8-Flash-Browser#5]
Hola

**Comment by ondaeduca** [comment]
hola Santiago,
he visto tu nombre en este repositorio y al ver que es español quería hacerle una consulta.
Soy javier de Onda Educa. Nuestra empresa tiene una plataforma en flash llamada Espacio Onda, estamos valorando varias opciones ya contrarreloj para poder continuar despues del finde flash. Ahora estamos hablando con Away, después de seguir un tiempo con Ruffle  el cual no va a llegar a tiempo. Quería consultarte si tienes experiencia en desarrollo de Electron para hacer navegadores con flash dentro. Tenenos uno desarrollado con CEF, pero sólo compatible para windows. Y estamos valorando todas las opciones. puedes contactarme por email en javier.yanez@ondaeduca.com si quieres y enviarme información tuya.
 Muchas gracias
 Un saludo
